#!/bin/bash
#
# Copyright (C) 2014 Wenva <lvyexuwenfa100@126.com>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

spushd() {
     pushd "$1" 2>&1> /dev/null
}

spopd() {
     popd 2>&1> /dev/null
}

info() {
     local green="\033[1;32m"
     local normal="\033[0m"
     echo -e "[${green}INFO${normal}] $1"
}

cmdcheck() {
    command -v $1>/dev/null 2>&1 || { error >&2 "Please install command $1 first."; exit 1; }   
}

error() {
     local red="\033[1;31m"
     local normal="\033[0m"
     echo -e "[${red}ERROR${normal}] $1"
}

curdir() {
    if [ ${0:0:1} = '/' ] || [ ${0:0:1} = '~' ]; then
        echo "$(dirname $0)"
    elif [ -L $0 ];then
        name=`readlink $0`
        echo $(dirname $name)
    else
        echo "`pwd`/$(dirname $0)"
    fi
}


#########################################
###           GROBLE DEFINE           ###
#########################################

VERSION=1.0.0
AUTHOR=smallmuou

#########################################
###             ARG PARSER            ###
#########################################

usage() {
cat << EOF
`basename $0` version $VERSION by $AUTHOR

USAGE: `basename $0` [OPTIONS] ssh-user@cloud-ip [local-ip:]local-port cloud-port 

DESCRIPTION:
    .

    ssh-user        The ssh user to access to cloud server.
    cloud-ip        The cloud server ip or domain.
    local-ip        The local ip to map, default is localhost.
    local-port      The local port to map.
    cloud-port      The port which local port to map to. note it must be an even number.

OPTIONS:
    -h              Show this help message and exit.
    -i              Assign ssh private key path.
    -p              Assign ssh port.
    -n              Assign name of the service name.

EXAMPLES:
    map2cloud root@120.24.18.12 22 22222
    map2cloud root@120.24.18.12 192.168.1.100:80 10080

EOF
exit 1
}

ssh_key_path=$HOME/.ssh/id_rsa
ssh_port=22
ssh_server=''
local_ip='localhost'
local_port=''
cloud_port=''
service_name=''

while getopts 'hi:n:p:' arg; do
    case $arg in
        h)
            usage
            ;;
        i)
            ssh_key_path=$OPTARG
            ;;
        n)
            service_name=$OPTARG
            ;;
        p)
            ssh_port=$OPTARG
            ;;
        ?)
            usage
            ;;
    esac
done

shift $(($OPTIND - 1))

[ $# -ne 3 ] && usage

[ `uname` != "Linux" ] && { error "only support linux os now."; exit -1; }

ssh_server=$1

local_parse() {
    if [ $# -eq 2 ];then
        local_ip=$1
        local_port=$2
    else 
        local_port=$1
    fi
}

local_parse ${2/\// }
[ -z "$service_name" ] && service_name=r-$local_port
cloud_port=$3

[ "`expr $cloud_port % 2`" != "0" ] && { error "cloud port must be an even number."; exit -1; }


#########################################
###            MAIN ENTRY             ###
#########################################

setup_service() {

file=/etc/init.d/$service_name

cat << EOF > $file
#!/bin/bash

# chkconfig: - 85 15
# description: map2cloud is a tool which map local port to cloud.

initdir=/etc/init.d
prog=$service_name
server=$ssh_server
rport=$cloud_port
ip=$local_ip
port=$local_port
mport=`expr $cloud_port + 1`
sshkey=$ssh_key_path
sshport=$ssh_port

start() {
    echo -n $"Starting \$prog: "
    nohup autossh -M \$mport -N -R \$rport:\$ip:\$port \$server -p \$sshport -i \$sshkey >/dev/null 2>&1 &
    echo "successed"
}

stop() {
    echo -n $"Stopping \$prog: "
    ps aux|grep \$rport|awk '{print \$2}'|xargs kill -9 >/dev/null 2>&1
    echo "successed"
}

status() {
    echo -n $"\$prog is "
    count=\`ps aux|grep \$rport|wc -l\`
    if [ \$count -gt 1 ];then
        echo "running ..."
    else
        echo "stoped"
    fi
}

restart() {
    stop
    start
}

case "\$1" in
    status)
        status
        ;;
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo $"Usage: \$0 {start|stop|status|restart}"
        exit 2
        ;;
esac

exit \$?

EOF

chmod +x $file
}

cmdcheck autossh
cmdcheck wc
cmdcheck ssh
cmdcheck chkconfig
cmdcheck ssh-keygen
cmdcheck ssh-copy-id

if [ ! -f $ssh_key_path ];then
    error "Not found ssh private key($ssh_key_path), please assign it or use ssh-keygen to generate it."
    exit -1
fi

info "Trying use ssh-copy-id to copy your ssh public key to server ..."
ssh-copy-id -p $ssh_port -i $ssh_key_path $ssh_server 2> /dev/null
if [ $? -ne 0 ];then
    error "Please copy ssh public key($ssh_key_path.pub) and append to your server authorize file(/root/.ssh/authorized_keys) manually."
    exit -1
fi
ssh -p $ssh_port -i $ssh_key_path $ssh_server echo 

info "Setup service $service_name ..."
setup_service

info "Enable $service_name startup ..."
chkconfig --add $service_name
chkconfig --level 345 $service_name on

info "Successfully. You can use command [service $service_name start/stop/restart/status] to control it."
